### ISSUE TITLE
Create tooling to import changes from canonical/lxd

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#11]
With Incus having renamed most files across the entire tree, it's near impossible to cherry-pick anything from the LXD repository.
As the fork should definitely be kept up to date, custom tooling that can programmatically handle the bulk of the file and function renames will be needed.

**Comment by tarruda** [comment]
Are the renames in dedicated commits or are they mixed with other changes? If they are in dedicated commits, it would be useful if there was an up to date list of commits that handled renaming here.

**Comment by stgraber** [comment]
It's a bit of a mess because there are a lot of different things that got renamed and a lot more to come.
That's probably going to be well over a hundred commit by the time the full rename is complete and most of those commits will be a mix of cosmetic and functional renames, so maintaining a full list is going to be quite hard.

The tool reference in this issue is going to have to both know about the renamed paths to adjust the diffs but also know about common patterns that have changed within the codebase, trying to mangle the commits it's reviewing so that most will just apply cleanly and the rest will apply with minimal manual involvement needed.

**Comment by tarruda** [comment]
The way I would approach the problem is by having two scripts:

- Symbol renamer script: This would spawn [Golang language server](https://pkg.go.dev/golang.org/x/tools/gopls), query symbols and  execute renaming/rebranding tasks in an automated way. The script should also be smart to understand which changes have already been made in the current codebase (seems straightforward since LSP allows querying symbols).
- Importer script: Argument the desired commit/PR that should be imported and works like this:
  - Clone the LXD repository
  - Checkout the parent of the commit being imported
  - Apply the renamer script
  - Save the changes in `tmp-parent` branch
  - Checkout the commit being imported
  - Apply the renamer script again
  - Save the changes in `tmp-current` branch
  - Run `git diff tmp-parent tmp-current` and save the outputs to a diff, which can then be applied to Incus master.

This could be fully automated with github actions, such as that when you open an issue title "Import LXD PR #NN", the workflow would run and send a PR to incus repository.

A prerequisite for this is that all changes are documented. Ideally, all the renaming tasks should have been executed by this tool. Even if you have to re-fork and reapply the changes (It would be worth IMO, as greatly facilitates importing future changes from LXD).

**Comment by stgraber** [comment]
That would probably work though I'm a bit worried about how slow that would be to run.

My current plan is to have a simple diff filtering/mangling logic which first applies all the known path renames and then applies a series of regexp to replace the most common occurrences of name changes.

That should be near instant and so long as that properly handles 90% of commits, it should be fine.

I already have pretty good tooling to handle large sets of git commits back from doing the LXD LTS releases. That tool could compare thousands of commits in seconds and had a basic text database on the side for all the commits that ever needed manual rework or that weren't suitable for backporting.

That's similar logic to what's used by the stable Linux kernel maintainers but in this case will need an extra intermediate step to mangle paths and common term renames.

**Comment by stgraber** [comment]
This tooling now exists and has been used to import LXD 5.17 and 5.18.
It's part of our stable-maintenance tooling which because it also handles embargoed security issues is a private repository within the lxc org, restricted to maintainers and those handling security relevant issues.
