### ISSUE TITLE
`incus shell` not preserving instance environment variables

### ISSUE THREAD

**Issue by Linkster78** [lxc/incus#1119]
# Required information

_Not relevant_

# Issue description

Using the `incus shell` alias does not inherit the environment variables configured on the instance.
This seems to be caused by `incus shell` being an alias to `incus exec <ctn> -- su -l`, with the login shell dropping the environment variables.

# Steps to reproduce

```sh
root@host:~$ incus launch -c environment.TEST=value images:debian/bookworm foo
Launching foo
root@host:~$ incus exec foo -- env | grep TEST
TEST=value
root@host:~$ incus shell foo
root@foo:~$ env | grep TEST
# nothing here...
```

# Information to attach

_Not relevant_

**Comment by stgraber** [comment]
`incus shell` is just an example alias which users can customize to their liking, we normally recommend using `incus exec` directly which is what's used throughout our documentation and leads to all environment variables being correctly set.

Usually one of the main point of getting a full login shell (`su -l`, `sudo -i`) is specifically that all pre-existing environment is thrown out and a new one put together from scratch based on the system configuration. That's why `su` doesn't allow you to pass `-p` alongside `-l` and why `sudo` doesn't allow you to pass `-E` alongside `-i`.

**Comment by simos** [comment]
An alternative is to add those environment variables to `/etc/environment` (in the instance). A login shell parses that file and will read those variables. 

I have sent a PR for the `incus alias` howto on this, https://github.com/lxc/incus/pull/1124/commits/f4c1fba5a65c335454176d18a0607b8f4f554321
