### ISSUE TITLE
Feature requirement: managed vlan awareness bridge 

### ISSUE THREAD

**Issue by thomasdba** [lxc/incus#1286]
Compared with other solutions , this feature is missing and better to have .
There is already a discussion here :
https://discuss.linuxcontainers.org/t/incus-networking-for-network-engineers/18405

**Comment by stgraber** [comment]
Incus can consume a VLAN aware bridge, but we currently don't have plans to start creating such bridges ourselves. That's because you typically need much more integration with the host operating system's network management.

The forum thread mentions VMWare. With VMWare you don't have a host OS, you don't have a Linux distribution that already has its own tooling to handle this, so it's not a problem for it to assume it owns the entire system and do whatever it wants.

With Incus we can't assume that we own the system and we generally try to stay away from that assumption.

**Comment by thomasdba** [comment]
but proxmox is like incus,rt? it also support vlan awareness bridge.

**Comment by stgraber** [comment]
No, it's not, Proxmox is efficiently an appliance, much closer to the VMWare story. You're not installing Proxmox on your laptop.
