### ISSUE TITLE
lxd-to-incus version mismatch

### ISSUE THREAD

**Issue by adamcstephens** [lxc/incus#133]
# Issue description

lxd-to-incus in tag incus-0.1 reports version 5.16. This is because lxd-to-incus is a completely separate go package and its parsing of the incus version is locked to what go.sum has.

# Steps to reproduce

1. Clone repo
2. cd cmd/lxd-to-incus
3. go build ./.
4. ./lxd-to-incus --version
5.16

# Other

I'm attempting to finalize packaging incus for nixpkgs. Am I correct to assume that this should be 0.1 to match the incus version? Would it be better to maybe version it on its own? Since it's using go packages for all the incus dependencies, does it benefit from being in this repo?

**Comment by stgraber** [comment]
It needs to stay in the repo so it can access the infernal packages but indeed will need a bit of tweaking to get the correct version as there's otherwise a bit of a chicken and egg problem.

The reason for the separate gomod is that we don't want the migration tool to cause the main gomod to include all of the LXD packages.

**Comment by adamcstephens** [comment]
Thank you!
