### ISSUE TITLE
Add ability to set the initial owner of a custom volume

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#1382]
For filesystem custom volumes, we currently have root:root as the initial owner of the volume.
This makes sense for system containers and VMs and is generally the correct behavior there.

But for OCI containers where the application may be running as non-root and where there isn't an init system to put the storage in place and correct ownership, having the ability to create a volume with a pre-defined owner would be quite useful.

This would likely look like 3 additional volume keys:
 - initial.uid
 - initial.gid
 - initial.mode

**Comment by codeignus** [comment]
This does work only for volume creation, but not when oci container is recreated where data is stored in volume for persistency.
On recreation of oci instance, this doesnt get same uid and gid probably because of mapping which I don't understand much about. But then oci doesn't start because now uid and gid of volume are different and that makes same volume that was created for persistency not be able to used more than once.

I tried with prom/prometheus image (initial.uid and initial.gid = 65534) and lot more(like linuxserver/jellyfin) had same issue with all of them.

**Comment by stgraber** [comment]
Try `security.shifted=true` on the volume, if your kernel can do it, that should avoid some of those kind of issues.

**Comment by codeignus** [comment]
`security.shifted = true` was one of the first things that I did try but it didnt change instance owner for that volume mount and instances still failed to start and `incus console --show-log prometheus` mention unable to write on those volumes

I am using debian 12 and zabbly package with latest stable version so kernel should be able to do it, but it doesnt make a difference unless I have to manually enable something
I still see same uid/gid on volume inside oci

incus storage volume show persistent-storage prometheus-data
config:
  security.shifted: "true"
  snapshots.expiry: 2w
  snapshots.schedule: '@daily'
  volatile.idmap.last: '[]'
  volatile.idmap.next: '[]'
description: ""
name: prometheus-data
type: custom
used_by:
- /1.0/instances/prometheus
