### ISSUE TITLE
"apt purge incus" does not delete network bridge incusbr0

### ISSUE THREAD

**Issue by divinity76** [lxc/incus#1545]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 24.04 (Noble)
 * The output of "incus info" or if that fails: 
 ```
 Error: The incus daemon doesn't appear to be started (socket path: /var/lib/incus/unix.socket)
```
   * Kernel version: 6.8.0-51
   * LXC version:5.0.3 is in apt...
   * Incus version: 6.0.0-1ubuntu0.2 
   * Storage backend in use: dir

# Issue description

"apt purge incus" does not delete the incus network bridge(s) incusbr0

# Steps to reproduce

 1. apt install incus
 2. incus admin init (and just accept the defaults)
 3. apt purge incus
 4. apt autoremove --purge
 5. ip address | grep -i incus
```
$ ip address | grep -i incus
74: incusbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.143.35.1/24 scope global incusbr0
76: vetha2670ca6@if75: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master incusbr0 state UP group default qlen 1000
```

# Information to attach
apt purge gives the following warnings:
```
rm: skipping '/var/lib/incus/guestapi', since it's on a different device
rm: skipping '/var/lib/incus/shmounts', since it's on a different device
dpkg: warning: while removing incus, directory '/var/lib/incus' not empty so not removed
```

i think it gave these additional errors the first time i ran it, but i can't 100% confirm that now, it gives less errors on re-install re-purge
```
dpkg: warning: while removing lxcfs, unable to remove directory '/var/lib/lxcfs': Device or resource busy - directory may be a mount point?
dpkg: warning: while removing lxcfs, unable to remove directory '/var/lib/lxcfs': Device or resource busy - directory may be a mount point?
```

**Comment by stgraber** [comment]
Looking at your output, you removed Incus while an instance was still running so that's not unexpected.

Incus will only turn off its mounts (shmounts, guestapi, ...) or shut down networks when there are no instances left. Otherwise it thinks that it's being shutdown for an update and therefore all of those components must keep running to avoid affecting the running instances.

I'd expect you to get a better behavior if you had first removed your instances prior to purging Incus.
That said, what you did will still work but I'd recommend rebooting your system to fully clear any leftover kernel objects (from network interfaces, to apparmor policies to anything else that container may have had loaded).

**Comment by stgraber** [comment]
(Closing as packaging issues should go to zabbly/incus in the first place and based on above, it's unclear that there really is much we can do in the packaging in the first place)
