### ISSUE TITLE
is there a roadmap for the first lts version's release

### ISSUE THREAD

**Issue by yachen4ever** [lxc/incus#312]
thanks for the great work. I've checked the docs carefully but could not find out when would the first lts release be released. could you kindly inform me since i been deploying my home server & wanna more stabilities without Canonical :) thanks in advance

**Comment by stgraber** [comment]
No roadmap but it will be in late March or early April.

That's because it's when the Linux Containers project issues LTS releases for all its major repositories, in this case, it will be LXC, LXCFS and Incus. The releases are synchronized and use the same version number, so in this case they will all go to version 6.0 LTS.

Our LTS releases happen every two years, get two years of bugfix and minor improvements followed by another 3 years of security only updates for a total of 5 years.

**Comment by stgraber** [comment]
Closing as not an issue but still happy to chat more in here if you have specific concerns.
