### ISSUE TITLE
Allow byte values in `limits.memory.swap`

### ISSUE THREAD

**Issue by dannycoin** [lxc/incus#541]
Is there a chance to limit the amount of swap memory an instance can use?

I understand that for RAM there is the option: limit.memory

**Comment by stgraber** [comment]
So I've been thinking about this one for a bit and I think it's possible to add something.

The confusing part is because of how swap is handled by the two cgroup versions.

Under cgroup1, swap is treated as an extra memory allocation on top of the main memory but without fine grained control of what's swap and what isn't.
So if you set limits.memory=1GiB limits.swap=512MiB, the kernel will indeed let you use 1GiB of RAM and then keep going by having another 512MiB of swap. But the kernel can also decide to make that 512MiB of RAM and 1GiB of swap if it's under memory pressure and there's no real way to prevent that (other than mess with swappiness).

Under cgroup2, I need to test the exact behavior. But it looks like you have `memory.max` for the total limit and then `memory.swap.max` (defaulting to `max`) for how much of this can be used as swap.


That means that with cgroup2 we would be able to have `limits.memory.swap` take a byte value which ends up being a subset of `limits.memory` that's allowed to be swapped. With the current `limits.memory.swap=true` making all of it available for swapping and `limits.memory.swap=false` making non of it available for swapping.

For cgroup1, we don't have any such control so the option would basically be useless. If we really wanted we could have it maybe tweak the swappiness based on how much swap you set, but that's about it.

(Unfortunately, distros have only recently started switching to cgroup2 by default on the server side, so we can't completely ignore cgroup1 for a number of years).

**Comment by stgraber** [comment]
Assigning this one to myself because I need to do some actual tests on the cgroup2 behavior to make sure it works as listed above.

If it works as an extra allocation on top of the main memory limit, then its behavior would be closer to the cgroup1 behavior and a different design would be needed (basically treating limits.memory.swap as an added allocation on top of limits.memory rather than as a subset of it, which would then affect how we enforce project limits and calculate server usage).
