### ISSUE TITLE
On RaspberryPI4: QEMU failed to run feature checks / Failed creating instance record. 

### ISSUE THREAD

**Issue by trebestie** [lxc/incus#606]
Hi all,
This is a follow-up of the #475 issue 

Manually add INCUS_OVMF_PATH=/usr/share/edk2/x64/ to incusd environment works in Voidlinux x64 system.

That fix can't be applied (or I do not know how) on a RaspberryPi4 since VoidLinux doesn't have edk2-ovmf package for aarch64 architecture.
So I switched to Fedora which provides such package and seems to have a proper incus.service file as well.

To setup incus vm I followed the section 'Start your first virtual machine' [here](https://github.com/ganto/copr-lxc4/wiki/Getting-Started-with-Incus-on-Fedora), but i got the the same QEMU error.

What I'm doing wrong?

My kind regards

**Comment by stgraber** [comment]
Hey there,

Support questions really should go to https://discuss.linuxcontainers.org as there is a much bigger active community over there (including the Fedora maintainer). Google is also generally better at indexing those forum threads for anyone else who may be running into this.

**Comment by stgraber** [comment]
(In this case, I'd recommend starting by looking at the incusd.log file and/or the journal output to get the full reason for why VM support isn't active)

**Comment by C0rn3j** [comment]
Could incus suggest to look at the log for the full error then? This is not very intuitive.

Ran into the same issue on Pi 5 running Arch Linux ARM, turns out the real error was `"Unable to run feature checks during QEMU initialization: Unable to locate a UEFI firmware"` in the log.

Really unsure where to nab the firmware from, as edk2, which I presume is the issue, is not packaged on ALARM.
