### ISSUE TITLE
incus-migrate usability issues when importing raw images

### ISSUE THREAD

**Issue by candlerb** [lxc/incus#660]
# Required information

Incus 0.6 on Ubuntu 22.04, full details as per #658

# Issue description

Several nits when using incus-migrate to import raw VM image files, when incus-migrate and the raw image file to be imported are both present on the local machine where incus is running.

0. incus-migrate isn't included in the apt packages, so you have to fetch it separately
1. incus-migrate refuses to run except as root. But I don't think that's necessary when reading an image file (as opposed to a block device or filesystem)
2. incus-migrate doesn't appear to be able to talk to the local incus daemon in the way that the `incus` CLI client can. This means you have to talk over a network socket, and set up an explicit trust relationship, which is inconvenient.
3. incus-migrate asks "Does the VM support UEFI Secure Boot? [default=no]:" (which sets `security.secureboot: "false"`), but it doesn't ask whether the VM supports UEFI boot in the first place. VMs which are only configured for BIOS booting also require setting `security.csm=true`, which is a bit of hidden magic.
4. incus-migrate loses the "sparseness" of sparse image files.

# Steps to reproduce

For the sparse file problem (4):

1. Start with a sparse image file. This one has ~5GiB data in a 50GiB image.

    ```
    # ls -ls /home/nsrc/nsrc-vm/output/nsrc-nmm.raw
    5851756 -rw-r--r-- 1 nsrc nsrc 53687091200 Mar 25 15:14 /home/nsrc/nsrc-vm/output/nsrc-nmm.raw
    # du -sck /home/nsrc/nsrc-vm/output/nsrc-nmm.raw
    5851756	/home/nsrc/nsrc-vm/output/nsrc-nmm.raw
    ```

2. Import using incus-migrate

    ```
    ...
    Would you like to create a container (1) or virtual-machine (2)?: 2
    Name of the new instance: nmm123
    Please provide the path to a disk, partition, or image file: /home/nsrc/nsrc-vm/output/nsrc-nmm.raw
    Does the VM support UEFI Secure Boot? [default=no]:
    ...
    ```

3. Check disk space used for the imported image

    ```
    # ls -ls /var/lib/incus/storage-pools/default/virtual-machines/nmm123/root.img
    52428864 -rw------- 1 root root 53687091200 Mar 25 15:18 /var/lib/incus/storage-pools/default/virtual- 
   machines/nmm123/root.img
    # du -sch /var/lib/incus/storage-pools/default/virtual-machines/nmm123/root.img
    51G	/var/lib/incus/storage-pools/default/virtual-machines/nmm123/root.img
    51G	total
    ```

I think this should be relatively easy to fix, by skipping over contiguous blocks of zeros when writing (regardless of whether the input was sparse). Explicitly seeking over them at source would also reduce network traffic, but this would involve the protocol carrying separate chunks with their own start offsets.

# Workaround?

The sparesness can be recreated manually using `dd`:

```
cd /var/lib/incus/storage-pools/default/virtual-machines/nmm123
dd if=root.img of=root.img.new conv=sparse bs=1024k

# ls -ls
total 58489932
52428864 -rw------- 1 root root 53687091200 Mar 25 15:18 root.img
 6061068 -rw-r--r-- 1 root root 53687091200 Mar 25 15:38 root.img.new

mv root.img.new root.img
```

I note that during bootup the message `error: sparse file not allowed.` appears. But it does appear to boot nonetheless.

```
$ incus start --console nmm123
To detach from the console, press: <ctrl>+a q
SeaBIOS (version rel-1.16.3-0-ga6ed6b7)
Machine UUID c1760506-6adf-4a04-a3aa-f0908459fb61


iPXE (http://ipxe.org) 05:00.0 CA00 PCI2.10 PnP PMM+3EFD3330+3EF33330 CA00



Booting from Hard Disk...
error: sparse file not allowed.
Linux version 5.15.0-1053-kvm (buildd@lcy02-amd64-103) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) )
Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-1053-kvm root=UUID=bd03690e-006e-4898-8233-e5896fd85cac ro console=tty1 console=ttyS0
BIOS-provided physical RAM map:
... etc
```

According to [this post](https://forum.manjaro.org/t/grub-error-sparse-file-not-allowed/20267/6), the error "sparse file not allowed" only relates to grub attempting to update `grub.env`, which isn't a major issue.

**Comment by stgraber** [comment]
> incus-migrate isn't included in the apt packages, so you have to fetch it separately

That's because the tool is meant to move stuff into Incus and so be run on non-Incus systems.
It's inclusion in the default package would just make any `incus<tab>` interactions annoying, not to mention, distros would most likely build the binary dynamically, making it unsuitable for transfer to an actual source system.

https://linuxcontainers.org/incus/docs/main/howto/import_machines_to_instances/ has links to pre-built static binaries which will work on any distribution.

> incus-migrate doesn't appear to be able to talk to the local incus daemon in the way that the `incus` CLI client can. This means you have to talk over a network socket, and set up an explicit trust relationship, which is inconvenient.

Yeah, same as previous point, it's a tool meant to be run on a remote source system, it's also designed to run identically on all operating systems, so it doesn't contain Linux-only logic like the unix socket support.

> incus-migrate asks "Does the VM support UEFI Secure Boot? [default=no]:" (which sets `security.secureboot: "false"`), but it doesn't ask whether the VM supports UEFI boot in the first place. VMs which are only configured for BIOS booting also require setting `security.csm=true`, which is a bit of hidden magic.

Yeah, would make sense to expose `security.csm=true` through a similar question in `incus-migrate`, I'll send a PR for that.

> incus-migrate loses the "sparseness" of sparse image files.

Yeah, we'd need a very different migration protocol to be able to handle sparse-ness, currently the VM data migration protocol is basically equivalent to `cat` over our API and so doesn't offer any way to truncate or seek which would be necessary for handling a sparse source.

Worth noting that there also isn't a good way to detect what bits are sparse when reading from a sparse source file, instead you're basically left having to do the same buffering + seek/truncate trick on copy.

As you mentioned, this could be done at receiving time, though I've not been particularly successful in finding a good Go package that can wrap an io.Writer to make it write a sparse file and properly fallback in cases where the underlying filesystem doesn't support it.

**Comment by candlerb** [comment]
> I've found a way to have incus-migrate handle the local Incus case with very limited changes needed, so we'll have that.

That will help hugely. Thank you!
