### ISSUE TITLE
Update documentations for Incus

### ISSUE THREAD

**Issue by ShalokShalom** [lxc/incus#85]
Currently, the README still links to the Ubunut documentation: 

https://github.com/lxc/incus/tree/main/doc

Would we host this on Netlify, or GitHub Pages, something of that sort?

**Comment by stgraber** [comment]
It's already hosted at https://linuxcontainers.org/incus/docs/main/

But we're waiting for a full update of our docs to fix all links.

**Comment by ShalokShalom** [comment]
Why? Where is the benefit in having outdated docs?

**Comment by stgraber** [comment]
Because either way they're wrong :)

The publishing for the docs is in place, but the content is all wrong and needs attention. This will all be done prior to an initial release of Incus but currently the focus is on getting the code right, getting the last few things that need to be removed, removed and getting packages that function. After that, it will be the time for a big documentation update as well as getting more of the website back online.

**Comment by stgraber** [comment]
Re-purposing this issue a bit, what we have left to do for Incus 0.1 is:
 - Update all lxd/lxc references in the docs
 - Remove any Canonical/Ubuntu branding
 - Tweak Sphinx to have the rendering line up with other Linux Containers project
 - Confirm that everything gets properly published on the website

**Comment by thePinochleKid** [comment]
@stgraber Is there already a branch for this?  Also, is a snap for incus yet?  Happy to take a stab at working on de-Canonicaling the docs.

**Comment by stgraber** [comment]
I'm currently working on it, mostly untangling a bunch of sphinx issues and then updating all the content.

**Comment by thePinochleKid** [comment]
Is there a part I can assist with specifically?

**Comment by stgraber** [comment]
Not at this time as I'm in a bit of a rush to get everything lined up for 0.1 later today but once the first pass on documentation is merged and live, I'd be great to have someone go page by page and make sure that they still make sense after all the edits :)

**Comment by thePinochleKid** [comment]
You got it!
