### ISSUE TITLE
RFC: Keep a fixed map between tag and releases

### ISSUE THREAD

**Issue by geaaru** [lxc/incus#855]
Hi guys,

thanks for all your work.

I have just a question. Is it possible to keep a fixed map between tags and releases to help bump scripts used to automatically create new packages of the last releases?

I like that from the first tags Incus followed the Golang way but the releases were with the old LXD way with only major and minor instead. 
The release 6.0.0 is been correctly mapped with the same version between the tag and release (6.0.0) so I updated the bump script to this new way.

With the tag 6.1.0 we are back with a release that ignores the patch version.

Is it possible to follow the same map between tags and releases always? Or what is the better logic to use?
If the patch release is equal to zero this means that the release is without the patch version?

Thanks in advance for any feedback.

**Comment by adamcstephens** [comment]
I think this is just a tarball issue? nixpkgs is using a git checkout and it's not a problem.

Though, in my opinion consistency is nice and I'd recommend consistent versioning everywhere rather than creating a mapping.

**Comment by stgraber** [comment]
Only releases that may release patch updates get a version string that includes a patch version. 

That's why you have Incus 6.0.0 but then Incus 6.1.


For convenience we do also provide symlinks for our tarballs so 6.1 is available at both: 
 - https://linuxcontainers.org/downloads/incus/incus-6.1.tar.xz
 - https://linuxcontainers.org/downloads/incus/incus-v6.1.0.tar.xz

So if your workflow favors always using semver then that symlink should work fine for your automation.

**Comment by geaaru** [comment]
@stgraber do you think that it's possible to enable indexes in the nginx directory `downloads/incus`?
So I will check directly the list of files there for new releases.

**Comment by stgraber** [comment]
Done, you now have indexes on https://linuxcontainers.org/downloads/
