### ISSUE TITLE
incus causes rsync backup to hang and never finish. 

### ISSUE THREAD

**Issue by hobson42** [lxc/incus#899]
# Required information

 * Distribution: ubuntu PRETTY_NAME="Ubuntu 22.04.4 LTS"
 * Distribution version:
 * The output of "incus info" or if that fails: Sorry - had to remove incus  to take backup, as it had not happened for a week!
   * Kernel version: Linux 6.5.0-35-generic x86_64
   * LXC version: 
   * Incus version: 6.1 
   * Storage backend in use:  ext4 

# Issue description
The file "/var/lib/incus/disks/default.img"  defeats rsync. The backup gets to that file, and just hangs, and never finishes. 
The drive tells me it is only 69GB used, but that file claimed to be 161GB in size. 

# Steps to reproduce

 1. Install incus
 2. Create a VM with a largish hard disk
 3. Boot VM from ISO and install ubuntu 24.04 LTS into vm
 4. attempt to backup the host drive, using rsync - The actual command (run as root) is 
 5. rsync -aAXv  \
--delete-during \
--exclude=/swapfile \
--exclude=/dev \
--exclude=/lost+found \
--exclude=/media \
--exclude=/mnt \
--exclude=/proc \
--exclude=/run \
--exclude=/tmp \
--exclude=/var/log \
--exclude=/home/*/.cache \
--exclude=/sys \
--exclude=/var/lib/lxcfs \
--exclude=/home/ian/logs \
--log-file=/home/ian/logs/cyllene.log \
/* /media/ian/driveE/cyllene

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
That's not really an Incus bug.

Those files aren't particularly special either. They're sparse files, so have a maximum size, in this case apparently of 161GB in your case.

Rsync must read through all files that were modified since the last run and will fail if the file gets modified while it's reading it. That makes it a very bad idea to backup those kind of extremely large files used for pool storage or even the VM storage files.

You're probably best to have rsync completely skip /var/lib/incus/disks/* and find a different way to handle backups of that data. If you must make a full backup of /var/lib/incus, then you should make sure that incus and all its instances are fully stopped first as there's no way you'll get a consistent backup of those disk images otherwise.
