### ISSUE TITLE
Feature request: Unprivileged UID/GID to consistent unprivileged containers

### ISSUE THREAD

**Issue by narcisgarcia** [lxc/incus#923]
Example in Debian 12 with using inclus 6.0 LTS from _bookworm-backports_ repository:
(using DIR storage pool)
```
$ sudo apt install incus
$ sudo incus admin init
$ incus launch images:debian/12 MyContainerName
Error: You don't have the needed permissions to talk to the incus daemon (socket path: /var/lib/incus/unix.socket)
$ sudo usermod --append --groups incus-admin $USER
$ newgrp incus-admin
$ incus launch images:debian/12 MyContainerName
$ sudo ls -l /var/lib/incus/storage-pools/local/containers/MyContainerName/rootfs
```
I see resulting files with same UID/GID range as host.
This means when guest is doing actions as guest's "root" is using same root UID&GID as host (and this reality is reflected in filesystem).
Although it could be applied with my host's user account,, any "incus-admin" group member has privileged permissions to manage containers, and I don't want to give any status like this to guest account.

**I'm asking to apply full "unprivileged" concept and I wish to see this also reflected on filesystem (and PIDs) same as the use of lxc.idmap by LXC.**
What I can see on a production scenario with transparent LXC unprivileged containers:
```
$ stat -c %u:%g /
0:0
$ cd /var/lib/lxc.u/lxc
$ sudo stat -c %u:%g MyContainerName1/rootfs
4032160:4032160
$ sudo cat MyContainerName1/config | grep -e idmap
lxc.idmap = u 0 4032160 65536
lxc.idmap = g 0 4032160 65536
$ sudo stat -c %u:%g MyContainerName2/rootfs
4818592:4818592
$ sudo cat MyContainerName2/config | grep -e idmap
lxc.idmap = u 0 4818592 65536
lxc.idmap = g 0 4818592 65536
```
I want to see mapping from host, and being applied overall on host PIDs UID/GID and on host inodes UID/GID.
I don't want any "unprivileged" guest can create files with host's UID 0 or run processes with host's UID 0 (or any other matching with host own users, eg. 1, 33, 1000, 1001).

With pure LXC, I adduser any user account (unprivileged), and run:
```
$ sudo -iu $UnprivilegedUser -- lxc-create -n MyContainerName -B dir -t download -d debian -a amd64 -r bookworm
```
This takes lxc.idmap from /home/lxc/.config/$UnprivilegedUser/default.conf ; for example:
```
lxc.idmap = u 0 4949664 65536
lxc.idmap = g 0 4949664 65536
```
and creates a rootfs with owners starting from uid/gid 4949664.
Host's UID 4949664 is guest's UID 0, and this means for me that any guest file (and guest PID) is really unprivileged at host scope.
Clear.
Simple.
Not only this but multiple unprivileged containers I create them with different UID/GID range, to be all unprivileged between them.

**Comment by stgraber** [comment]
This isn't something we're interested in doing.

As you mentioned, we have LXC which can be used fully unprivileged (with the usual setuid helpers) and can operate completely as your own user. This obviously comes with many limitations on what it can do with storage, networking and device passthrough.

Incus is designed around being network driven through a REST API and so, by design, does not understand or care about local users.

It's possible to restrict what a given API user (TLS certificate or OIDC identity) can access by limiting them to specific projects and further restricting what that project has access to.

But in all cases, Incus remains running as fully privileged root and just applies security restrictions based on those internal configurations.


Putting a user in the `incus-admin` group gives you full admin access over the entirety of Incus which is indeed not recommended for a guest user.

That's what the `incus` group is for, members of that group do not have access to the main unix socket but instead access a secondary socket handled by our `incus-user` process which then dynamically creates projects and restricts the user to that project.

In this situation, the user effectively gets restricted to only running unprivileged containers or VMs, is limited to a user-specific network and can only passthrough paths within their home directory or setup direct uid/gid mapping of their own uid/gid.


This provides an environment that's safe for unprivileged users to use without providing them with a way to escalate to full root privileges.


You also mentioned wanting to have containers not shared their uid/gid range.
This can be done by setting the `security.idmap.isolated=true` config option directly on an instance or in a profile. It will by default limit the instance to 65536 uid/gid.


Our on-disk storage remains unshifted on recent kernels as storing the data shifted is costly (requires rewrite of all the metadata), it's racy (if a crash happens mid-shift, we can't recover) and error prone (we have logic for uid/gid, ACLs and fscaps xattrs but there may be other file properties that should be shifted and currently aren't).

That's why we first did the work to develop `shiftfs` and later on the `VFS idmap` feature in the Linux kernel, specifically so the files on-disk do not need to be shifted to be used by unprivileged containers.

Only the root user has access to the on-disk data directly as for everyone else we have extremely restrictive permissions on our directories to prevent traversal to any of that data by non-root users. LSMs can be used to further enhance that protection if required and we've recently been investigating ways to keep all host visible data as noexec (even by root) for further safety.
