### ISSUE TITLE
Root filesystem with nodev mounted may case SRIOV device configure problem.

### ISSUE THREAD

**Issue by ncwhale** [lxc/incus#965]
# Required information

 * Distribution: Arch linux
 * Distribution version: 2024-06-28
 * The output of "incus info" or if that fails:
   * Kernel version:  6.6.8-arch1-1
   * LXC version: 6.0.0
   * Incus version: 6.2
   * Storage backend in use: zfs 

# Issue description

I'm using LXC/incus on my Host to run OpenWRT as a router for my homelab.

When I try to pass the SRIOV infiniband device to openwrt container, got this error message:

`Can't create device as devices path is mounted nodev`

BTW, I just use 'mount' and saw my root filesystem (also ZFS) mounted as nodev, but `/var/lib/incus/devices` was in it, is that the case?

# Steps to reproduce

 1. edit `/etc/modprobe.d/mlx4.conf`,  config as  `options mlx4_core port_type_array=1,2  num_vfs=4,2,2  probe_vf=4,2,2`
 2. edit grub.conf, add `intel_iommu=on iommu=pt` for kernel 
 3. reboot server
 4. `lspci -nnk` to ensure sriov device is show.
 5.  `incus config device add openwrt ibo0 infiniband nictype=physical parent=ibo1v0`
 Error: Failed to start device "ibo0": Can't create device as devices path is mounted nodev
 6. ` incus config device add openwrt ibo0 infiniband nictype=sriov parent=ibo1`  # This is also a confuse error
 Error: Failed add validation for device "ibo0": Invalid value for device option "hwaddr": Invalid value, must be either 8 or 20 bytes of hex separated by colons
 7. ` incus config device add openwrt ib0 infiniband nictype=sriov parent=ibo1 hwaddr=2e:bd:9f:f6:e4:e8:e6:f4`
 Error: Failed to start device "ib0": Can't create device as devices path is mounted nodev

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/incus/incusd.log) [incusd.log](https://github.com/user-attachments/files/16026476/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by ncwhale** [comment]
Addon: After set the `device=on` flag on root and restart incus.service, it works.

**Comment by stgraber** [comment]
Yeah, I'm not sure that there is anything for us to fix here. We usually try to bind-mount whatever we can to avoid having to create device nodes, but on occasion, like infiniband where we need to create some support devices, we do need to create devices into /var/lib/incus/devices/

On 99% of systems, that's fine as `nodev` is usually reserved for home directories and things like /run (which is why we don't put our devices in `/run/incus/devices`) but on the odd system which does have /var/lib set as nodev then things fail.

We do have detection code for that which then results in that error, so things seem to work as expected here.

@ncwhale I'm going to close this one as I'm not seeing an actual issue. The MAC address thing does seem like an issue. I suspect our Infiniband code is just using a normal MAC address generator for the IB device rather than generate something using the longer MAC address format for IB. It'd be good to have a separate issue to handle this one!
